### ISSUE TITLE
Refactor how we store size/weight for pets

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#14]
~Currently the size column on Pets table is a string that is populated with pre-determined ranges in a form select. This should be refactored. The column name should be `weight` with `json` data type. Then `pet.weight` would become a hash `{ "from" => '10', "to" => '15', "unit" => "lb"}` and we should have inputs for these three key value pairs in the pet CRUD form.~

See below for acceptance criteria.

**Comment by Thrillberg** [comment]
I'm not 100% sure of this design. Generally I'm not a fan of db tables with `json` data types because the data can easily get messed up and become hard to debug. Can we introduce a new table, perhaps `weights`, with these columns:
`from : integer`
`to : integer`
`unit : string`
`pet_id : integer` (foreign key)

**Comment by kasugaijin** [comment]
Certainly. I am happy to go that route. New table, weights that belongs to pet per the above schema.

**Comment by kasugaijin** [comment]
I can take this one.

**Comment by kasugaijin** [comment]
https://github.com/rubyforgood/pet-rescue/pull/125
closed
