### ISSUE TITLE
Organization Type

### ISSUE THREAD

**Issue by jadekstewart3** [rubyforgood/pet-rescue#172]
As an organization admin, when I visit "admin/organization/:org_id/edit", I see a drop drown down field. In that drop down field I see options to establish my organization as 
- 100% Adoptions
- 100% Fostering 
- Hybrid
When I select on of these options and click the "Save" button, I am shown a confirmation message.

**Comment by yuricarvalhop** [comment]
Hey @jadekstewart3, I could do this one. 

You reckon this should be under OrganizationProfile or on the orga table itself?

**Comment by jadekstewart3** [comment]
@yuricarvalhop My first thought is the organization table. @edwinthinks @kasugaijin @nsiwnf what do yall think?

**Comment by kasugaijin** [comment]
> @yuricarvalhop My first thought is the organization table. @edwinthinks @kasugaijin @nsiwnf what do yall think?

I see this ratio as something that could change over time, and right now, we're setting it up so the Org has control over data it wants to change via its profile. So, I'd see it living on the organization profile. The Organization itself just has name and slug, and I think it an object less likely to change over time. I think it's good to keep the Organization light if we can, and load up the Profile. Open to other ideas though!

**Comment by yuricarvalhop** [comment]
@kasugaijin is the idea that fields on the organization table almost never change? How often does an orga change their type? 
Should the name or slug also be moved into the profile in the future?

**Comment by kasugaijin** [comment]
@yuricarvalhop so I think the Organization table will remain as is with name and slug, and all other information can go on the profile. The reason is because we use multi-tenancy with the organization model being the the base model that all others are scoped under. So, we need to keep the slug on the Organization model as we use that for routing. The name technically could move to the Profile, I guess, but I think that can be moved only if there is a need to.

**Comment by kasugaijin** [comment]
On hold until we build out some more foundational stuff.
