### ISSUE TITLE
Skip failing tests so that our build becomes green so that we can come back to it later

### ISSUE THREAD

**Issue by edwinthinks** [rubyforgood/pet-rescue#180]
Based on our conversation, let's skip all the failing tests so that the build is green

**Comment by kasugaijin** [comment]
I took a peak at what is failing:

- the integration tests that are asserting HTML elements can be deleted since we have a brand new UI
- controller and model errors - some of these are functionality relevant still, so I suggest we either try and fix them. Perhaps that could be another snack issue separate from removing what can be removed. 
- Let me know if you have any questions!

**Comment by jadekstewart3** [comment]
@kasugaijin I commented out all of the failing tests leaving the title as a skeleton outline for when we go back and start re-testing  :) I didn't find any failing model tests. I would be interested to pair on repairing the controller tests if you're up for it!

**Comment by edwinthinks** [comment]
Done via #184
