### ISSUE TITLE
Staff can upload and remove images for a pet

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#259]
As staff I can navigate to pet/show and go to the files tab to add a new file and delete an existing file

Acceptance criteria
- use existing file type, size validations
- limit to five images 
- each image has a row with image, filename, and delete option
- uses same table as staff table, but experiment with a larger image!

**Comment by torresga** [comment]
May I work on this, please?

**Comment by kasugaijin** [comment]
All yours! @torresga

**Comment by torresga** [comment]
Hi there @kasugaijin , as I am looking at this further, I realize this task is potentially blocked by https://github.com/rubyforgood/pet-rescue/issues/256 and  https://github.com/rubyforgood/pet-rescue/issues/257 since they all involve first creating the tab functionality. I see that there is this PR https://github.com/rubyforgood/pet-rescue/pull/265/files that creates the tabs using partials and the `nice_partials` gem that you already agreed to. Should I base my work on that PR? That way the scope of this ticket can just be adding the Files partial, and I won’t have to worry about re-implementing the tabs. Thanks!

**Comment by kasugaijin** [comment]
@torresga yes good catch! I hope to get around to reviewing that PR in a bit and then we can get it merged in so it can unblock this work.

**Comment by kasugaijin** [comment]
@torresga I took a look at https://github.com/rubyforgood/pet-rescue/pull/265 and like the approach. I'll await @ErinClaudio for when he is ready for review so we can merge (no rush!).
