### ISSUE TITLE
Spike on Form builder architecture

### ISSUE THREAD

**Issue by Thrillberg** [rubyforgood/pet-rescue#388]
![image](https://github.com/rubyforgood/pet-rescue/assets/10481391/8fa84f7a-d6aa-4f81-a31e-5fa4a78df327)

Notes from Mae:
>Another note, it knows which kind of Response input to display bc Question has both name and input_type

>My Response has fields for each kind of input type to simplify, so, fields are:
string_value
integer_value
file_value
boolean_value
array_value

>The Checklist/Tasklist builder was built the same way so as to store the List (Form) separate from the Assignments (Responses).

**Comment by Ptrboro** [comment]
Hey, I wasn't part of the Spike discussion, so I might be missing some context, but I'm concerned that updating or deleting a question could mess up the historical response data. E.g. if a question is deleted, all associated responses would also be removed. I think keeping historical data is crucial, especially since it may contain important information like adopter contact details, and losing such data could be problematic.

But I think there's a straightforward solution. We can add question_text and input_type fields to the Response model and when creating a response, we should copy this information from the Question. This way, even if the question is later updated or deleted, we'll still have a record of the original question text at the time the response was submitted. It might also be necessary to modify or remove the foreign_key constraint between the Response and the Question models (so we can delete Question, without losing Responses).

I hope this is helpful :) We can also add this later if needed and keep the solution simple for now.

**Comment by Thrillberg** [comment]
Thanks for raising the valid concern @Ptrboro ! I wonder if @edwinthinks 's idea of soft deleting would be sufficient? If we do that then we wouldn't have to add redundant data elsewhere. We could also use [the gem `papertrail`](https://github.com/paper-trail-gem/paper_trail) to keep track of versions of Questions (not sure if this addresses the need around Question deletion though). What do you all think?

For now, it's probably best to make Questions unable to be updated or deleted just for simplicity but I think we'd want to support updates/deletion in the future.

**Comment by Ptrboro** [comment]
@Thrillberg @edwinthinks soft-deleting will fix the problem for deleted questions but not for updated ones 🤔 It will be common for people to change the text of a question instead of deleting and creating a new one. Non-tech people won't be aware that responses are linked to questions and changing the question text will change how the old submissions look like. Papertrail is worth researching but it's a big framework and may have its own set of challenges.

But I think we all agree to start with a simple and solid foundation and add this logic later :)

**Comment by maebeale** [comment]
I'm in favor of @Ptrboro's suggestion to cache the original question data over soft delete (because of the update scenario).

I've got this in the wild and there, I've been able to train users to make a new question when the fundamental meaning is changed. I also have a text_override field on FormQuestion so if they want it to display differently on one Form, they can do that without changing the question and we have record of what was on that Form. 

But @Ptrboro's solution is both cleaner and more performant.
