### ISSUE TITLE
Placeholder image for pets that do not have pictures uploaded

### ISSUE THREAD

**Issue by nsiwnf** [rubyforgood/pet-rescue#415]
As an adopter or staff, I should see a placeholder image instead of a broken image link for pets that do not have pictures

<img width="364" alt="Screen Shot 2024-01-04 at 8 01 42 PM" src="https://github.com/rubyforgood/pet-rescue/assets/34173394/427a000f-54fc-485e-bf1e-d413287189d8">

---

Some suggestions:
https://stock.adobe.com/search/images?k=no+image+available

**Comment by digeshparecha** [comment]
May I take this?

**Comment by Ptrboro** [comment]
@nsiwnf I think we already have this:
<img width="311" alt="Screenshot 2024-01-08 at 16 36 35" src="https://github.com/rubyforgood/pet-rescue/assets/16762860/ac8f3624-16f7-4d94-8d55-df8e53d24717">

What you see in your screenshot is not a missing image, but a broken one. This is because ActiveStorage is set up to store images locally, but Heroku does not provide persistent local storage. As a result, files saved on disk in staging env are removed after a while, causing broken links in `<img>` tags. To resolve this, we need to reconfigure ActiveStorage to use a persistent storage like Amazon S3.

**Comment by kasugaijin** [comment]
Thanks @Ptrboro !

**Comment by nsiwnf** [comment]
@Ptrboro Thank you!
