### ISSUE TITLE
Staff Dashboard UI - As staff I can toggle the side navbar on the dashboard to hide/show

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#608]
Currently in our dashboard, the sidenav will hide automatically if the screen width gets narrow enough. In our theme, one should be able to click the hamburger to toggle the side navbar to display/hide. We need this functionality working in our dashboard. See video for demo.

https://www.loom.com/share/29d24645fe524b20904ca6f50fece745?sid=9359007a-cc46-4d23-ba5e-ae560d3a0618

**Comment by kasugaijin** [comment]
@jp524 All yours!

**Comment by jp524** [comment]
I had the chance to look at this issue. My understanding is that the Geeks UI JavaScript needs to be added (#176 added just the CSS).
This is because Geeks adds the class `toggled` to the div with `id="db-wrapper"` when clicking on the hamburger button. This `toggled` class takes care of showing/hiding the side navbar.

I don't think I can add the Geeks JS file myself since I don't have the source code.

Alternatively, I can create a Stimulus controller to add that `toggled` class so that we don't add the Geeks JS file. @kasugaijin Please let me know which method you prefer.

**Comment by kasugaijin** [comment]
@jp524 thanks for looking into it! I am not sure why that particular JS is missing yet other JS from the theme is present. To be honest, I don't even know where the existing theme JS is located. I can see the images from the theme in app/assets but no JS. I am not opposed to using a Stimulus controller to get it working...and if we want to investigate further to figure out why the theme JS is not included we can at a later date.
