### ISSUE TITLE
I18N - find places where we have not used I18N and add copy to en.yml

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#737]
We started off well adding text displayed in the UI (view copy, alert messages, and active record error messages) in the I18n en.yml file, but then we got a bit forgetful. 

This task is to look through the application and find cases where we should move text from a view to en.yml, a controller (e.g., alert messages), and also add copy in en.yml for active record validation error messages. 

I am not specifying a set amount of work for this task as I don't know how many places this occurs. If you prefer, you can scope the work and report back, or just start making the changes and make a PR resource by resource.

**Comment by wandergithub** [comment]
Can I work on this issue?

**Comment by jmilljr24** [comment]
@wandergithub just an fyi, in #738 which will be merged soon I added a method which you can use for translating enum's if you get to those in this issue. Let me know if you have any questions about it.

**Comment by wandergithub** [comment]
@kasugaijin Hi, after working and investigating this issue I've noticed that updating translations in big chunks has led to some translations being missing due to managing too much of them.

I don't know what you guys would like me to do with #791 or if you want me to continue with the views to manage to close this issue. But I've been thinking it would be better if the translations are added while working with code and changes related to them in isolated ways. Like a gradual work/progress on upcoming PRs. Now it should be easier with the rules while we reinforce the use of I18n in the reviews. I can help with that too.

**Comment by kasugaijin** [comment]
@wandergithub I'd say do as much as you are comfortable doing in the PR, then we can try address the rest in related work. The only issue with leaving it to other work is that it will probably be forgotten about, and there may be areas that do not get any focus for a while, if at all. But, that said, I don't want this to become uncomfortably large for you either.

**Comment by wandergithub** [comment]
I will wrap up my contributions to the translations with this last PR. Moving on to addressing other topics.

**Comment by Meri-MG** [comment]
Hello, @kasugaijin, can I start working on this issue?

**Comment by kasugaijin** [comment]
@Meri-MG hey this issue got split into two other issues that were picked up. I should close this issue. Sorry about that. Is there another ‘ready’ issue you are interested in?
